services:
  counter:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./db.sqlite
        target: /app/db.sqlite
        bind:
          create_host_path: true
    restart: unless-stopped
